FROM nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive 

WORKDIR /app
COPY . .

RUN mkdir -p ~/.insightface/
RUN mv models ~/.insightface/

RUN apt update
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update
RUN apt install python3.7 python3.7-dev python3-pip -y
RUN python3.7 -m pip install --upgrade pip
RUN apt install ffmpeg libsm6 libxext6  -y
RUN pip install mxnet-cu112 flask jsonpickle
RUN cd python-package && pip install . && cd ..

RUN export PATH="/usr/local/cuda/bin:$PATH" 
RUN export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"

CMD ["python3.7", "app.py","--gpu-id", "0"]
