FROM nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive 

WORKDIR /app

RUN apt update
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update
RUN apt install python3.7 python3.7-dev python3-pip python3.7-distutils -y
RUN python3.7 -m pip install --upgrade pip
RUN apt install ffmpeg libsm6 libxext6 -y
RUN pip install mxnet-cu112 flask jsonpickle

RUN export PATH="/usr/local/cuda/bin:$PATH" 
RUN export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
ENV MXNET_CUDNN_AUTOTUNE_DEFAULT=0 

COPY . .
RUN mkdir -p ~/.insightface/
RUN mv models ~/.insightface/

RUN cd python-package && pip install . && cd ..

CMD ["python3.7", "app.py","--gpu-id", "0"]
